### ISSUE TITLE
There was an error with the XML retrieved from thetvdb.com

### ISSUE THREAD

**Issue by thezoggy** [dbr/tvdb_api#45]
```
>>> import tvdb_api
>>> t = tvdb_api.Tvdb()
>>> show = t['Sugar and Spice']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tvdb_api.py", line 877, in __getitem__
    sid = self._nameToSid(key)
  File "tvdb_api.py", line 857, in _nameToSid
    selected_series = self._getSeries( name )
  File "tvdb_api.py", line 643, in _getSeries
    allSeries = self.search(series)
  File "tvdb_api.py", line 624, in search
    seriesEt = self._getetsrc(self.config['url_getSeries'] % (series))
  File "tvdb_api.py", line 575, in _getetsrc
    raise tvdb_error(errormsg)
tvdb_exceptions.tvdb_error: There was an error with the XML retrieved from thetvdb.com:
not well-formed (invalid token): line 7, column 68
```

Looking at XML for show:
http://thetvdb.com/api/9DAF49C96CBF8DAC/series/78252/all/en.xml

We can see its because html is in the overview:
```
<Overview>Welcome to the Sugar and Spice guide at TV Tome. <p align=left> Loretta Fontaine and Vickilyn Fontaine Clayton, two black sisters living in a small Oklahoma town who attempt to raise their rambunctious teenage niece, Toby Reed (played by La Verne Anderson) after her parents are killed in a car accident. Vicklyn runs a curio shop called Small World Miniatures, and Loretta is a hostess at Cafe Jacques. All three live at 731 Oakwood Avenue in Ponca City. <p align=left>First Telecast:March 30,1990 <p align=left>Last Telecast:May 25, 1990 <p align=left>Episodes: 7 color episodes. <p align=center> CBS Broadcast History <p align =center>March-May 1990----Fridays----9:30
<p align=center>May 1990----Fridays----8:30
<p align=center>Theme song: <p align=center> Performed by Loretta Devine and Vickilyn Reynolds</Overview>
```

Another one,
```
>>> show = t['Someone Like Me']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tvdb_api.py", line 877, in __getitem__
    sid = self._nameToSid(key)
  File "tvdb_api.py", line 857, in _nameToSid
    selected_series = self._getSeries( name )
  File "tvdb_api.py", line 643, in _getSeries
    allSeries = self.search(series)
  File "tvdb_api.py", line 624, in search
    seriesEt = self._getetsrc(self.config['url_getSeries'] % (series))
  File "tvdb_api.py", line 575, in _getetsrc
    raise tvdb_error(errormsg)
tvdb_exceptions.tvdb_error: There was an error with the XML retrieved from thetvdb.com:
mismatched tag: line 8, column 93
```

Looking at XML:
http://thetvdb.com/api/9DAF49C96CBF8DAC/series/78253/all/en.xml

We can see its because html is in the overview:
```
<Overview>Welcome to the <B>Someone Like Me guide at TV Tome.
There is no editor for this show. If you would like to be the editor look here for details.</Overview>
```

Fixing these manually.. rumor is that new tvdb site is coming soon (heard that before.. ) since this has been an ongoing issue forever on this site.. any advice on how to just prune html out of that damn overview field? Or if we wanted to just nuke that field?

**Comment by thezoggy** [comment]
fyi new site getting closer.. draft of tvdb new api - https://drive.google.com/file/d/0B25LBca0qlnuU1YyUEtKSkhnRkE/view

**Comment by chrisspen** [comment]
Why was this closed? This error is still occurring.

**Comment by thezoggy** [comment]
i stopped relying on this lib and moved on..  issue was 1 year outsanding by the time i closed it.. and its been 3 years since..

**Comment by dbr** [comment]
Closed because it was a problem with thetvdb.com, not this library (they were producing invalid XML which tvdb_api library cannot parse)

For now, and problem series need fixed manually(removing bad characters from the show description etc - as described earlier on this ticket), or, by posting in thetvdb forums

Longer term, there is a new version of the API, which this wrapper should be updated to use. There is a separate ticket about this

**Comment by chrisspen** [comment]
@dbr, I just don't think it's reasonable to expect clean descriptions from TVDB, especially considering here we are, 3 years later, still seeing the same errors. There are ways to clean and fix malformed HTML/XML, such as with tidylib. If we know the problem is restricted to just a <overview> tag, a simple regex could even be used to strip out tags.

**Comment by thezoggy** [comment]
this issue is actually much bigger than you think, tvdb has been plagued with people putting malicious links in show overview (link to malware/or streaming sites) so pruning out html from the field is something that should be done to safeguard people.. both on their and the lib side.. 
https://forums.thetvdb.com/viewtopic.php?f=4&t=37093
