### ISSUE TITLE
Access season plot synopsis

### ISSUE THREAD

**Issue by MartijnBraam** [dbr/tvdb_api#56]
The season has no data. Can access to the season plot/description be added?

**Comment by dbr** [comment]
Excuse the slow reply, but.. I'm not sure what this refers to - there isn't a per-season overview as far as I can tell.

The series (aka show in `tvdb_api`) and episode overviews are accessible via the `overview` attribute:

```
>>> t = tvdb_api.Tvdb()
>>> t['Scrubs']['overview']
...
>>> t['scrubs'][1][2]['overview']
...
```

These map to the series overview in the API
https://api.thetvdb.com/swagger#/Series
and episode overview
https://api.thetvdb.com/swagger#/Episodes
..but there's no concept in the API of a season attributes

I'll close this for now as it is quite an old issue - reopen if this is still relevant!
