### ISSUE TITLE
Combine Multi-Season Episodes Into Single Season

### ISSUE THREAD

**Issue by Pazran** [dbr/tvdb_api#59]
Can i retrieve episode name using episode only without season? So for example:

season 1 has 50 episodes
season 2 has 50 episodes

Is it possible to just use episode 60 to get season 2 episode 10 name?

**Comment by PragmaticNet** [comment]
You can use the .search() method with a key to find the nth episode.

t = Tvdb()
t["seriesname"].search(60, key='absoluteNumber')

**Comment by dbr** [comment]
Yep searching via the absoluteNumber attribute is the right way to do this

Hmm, it might be worth adding a helper shortcut to this like `Tvdb(...)['show name'].aired_on()` but shall leave this for now until it comes up again
