### ISSUE TITLE
Anomalous behavior for recent shows in TVDB.api

### ISSUE THREAD

**Issue by Fever1223** [dbr/tvdb_api#67]
I'm experiencing a problem retrieving recent TV show overviews from TVDB

Specifically, I call the episode overview from the TVDB database, thus:

```
#!/usr/bin/python   
# getoverview.py
import sys, tvdb_api   
t = tvdb_api.Tvdb()   
episode = t [str(sys.argv[1])] [float(sys.argv[2])] [float(sys.argv[3])]   
ov = episode['overview']   
print ov.encode('UTF-8')
```
For shows before May 1, typing `getoverview.py Homeland 7 11`, for example, returns "Saul's mission is a go. The clock ticks on the Keane administration.", as expected.

For shows that aired their first episodes after May 1, however, typing `getoverview.py Sweetbitter 1 1` or `getoverview.py "Cobra Kai" 1 6` returns errors:

```
Traceback (most recent call last):  
  File "/usr/local/bin/getoverview.py", line 9, in <module>
    print ov.encode('UTF-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```
I have verified that the episode overview is present on the web page for both these examples.

I am using tvnamer 2.4, updated flexget to the current version, and both of these appear to link to tvdb.api(), so whatever error I am making is a subtle one (at least to me). Help would be appreciated.

**Comment by dbr** [comment]
That's strange - I'm not sure why the overview attribute would have been None

I can't seem to replicate this now - shall close this for now, reopen if this is still a problem, although I guess this might have been a temporary weirdness with TheTVDB.com maybe
