### ISSUE TITLE
Choose Show from list

### ISSUE THREAD

**Issue by josopu** [dbr/tvdb_api#71]
Hey! Thanks for this nice API.

I would like to know if it is possible to let me choose which Show is the most accurated for my search because when I search it on the API it says "cannot find show on TVDB" but I do on web, when they list me possible matches.

So, I only wanted to know how to do this via API if it's possible.

Thanks again for all your work.

**Comment by dbr** [comment]
The module is a fairly direct mapping to the API,

https://api.thetvdb.com/swagger#!/Search/get_search_series

In theory, the search API should be the same as searching via the web, but this doesn't always seem to be the case.. What the difference is would probably be a question best for TheTVDB site itself, maybe on their forum? The web search might normalise the search terms like, say, replacing "&" with "and" etc etc

**Comment by dbr** [comment]
(closing this for now; reopen if there is anything that can be done or at least documented on this module's side of things!)

**Comment by rtaft** [comment]
Searching for 'Game Of Thrones' returns 'Game of Thrones: Cartoon Parody'.  I can get around it by passing in the ID but this feature would be nice.
