### ISSUE TITLE
Recent API Change

### ISSUE THREAD

**Issue by bulge4024** [dbr/tvdb_api#72]
No longer works due to tvdb api changes.
403 Error

**Comment by jim1138** [comment]
> No longer works due to tvdb api changes.
> 403 Error

What version are you running?

I had a similar problem and finally worked out I'd got v1.9 of the tvdb_api installed via tvnamer 2.2.1-1.

I removed them:-
```
sudo apt remove tvnamer
sudo apt autoremove # to remove the tvdb_api package
```
then installed tvnamer 2.5 using pip
```
pip install tvnamer
```
This cleared the problem up for me.

**Comment by bulge4024** [comment]
Followed your advise and updating worked! Wrapper is now getting the Show Name, Episode Name, Episode Plot but not the tvdb show ID and I am also getting another error now and unsure how to find the cause.

Error: Unknown column 'None' in 'where clause'

Any suggestions?

**Comment by dbr** [comment]
The show ID should be available via the `show['id']` attribute, e.g
```
>>> t['scrubs']
<Show 'Scrubs' (containing 10 seasons)>
>>> t['scrubs']['id']
76156
```

The rest of the error doesn't seem to be directly caused by `tvdb_api` - it looks like an error with an SQL query, one of the parameters being passed a `None` unexpectedly
