### ISSUE TITLE
Says show doesn't exist although it does

### ISSUE THREAD

**Issue by PortStone** [dbr/tvdb_api#80]
`t[253463]` gives me `tvdb_api.tvdb_error: not found` although it clearly exists as you can see here: https://thetvdb.com/series/black-mirror

**Comment by mueslo** [comment]
duplicate of #73

**Comment by dbr** [comment]
Yep per as the ticket @mueslo refers to, TheTVDB currently returns an error 404 when trying to get actors for a valid show with no recorded actors. Confusing but we can workaround this in the API.

I've created #85 to track this

**Comment by PortStone** [comment]
I created a thread on the forums (https://forums.thetvdb.com/viewtopic.php?f=17&t=65827).
