### ISSUE TITLE
Not authorized api error changed

### ISSUE THREAD

**Issue by the01** [dbr/tvdb_api#84]
`tvdb_api` checks for `Not Authorized` as the error message, but it is now `Not authorized`.

Maybe we could also check the http status code and/or do a lower case string comparison.

**Comment by dbr** [comment]
Thanks for the report! This has been fixed in 9f63511477cd4992be01a7272c1e25edaea393b8 which will be part of the next release (probably numbered v3.1)

**Comment by the01** [comment]
ah, sorry, I didn't check master.
